#!/usr/bin/env bash

echo "Base install without monitoring"

sudo apt-get install docker
sudo apt-get install docker-compose
sudo apt-get install git
git clone https://github.com/loisoj/yupe-docker.git
chmod +x ~/yupe-docker/yupe
cd yupe-docker
~/yupe-docker/yupe set-env dev
~/yupe-docker/yupe alive
docker ps
